<?php

namespace Database\Factories;

use App\Models\Project;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/** @extends Factory<Project> */
class ProjectFactory extends Factory
{
    protected $model = Project::class;

    /**
     * Production codes are generated by ProjectService. The factory sets a
     * unique code directly so tests can create independent project records.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $user = User::factory();
        $startDate = fake()->dateTimeBetween('-1 month', 'now');
        $targetDate = (clone $startDate)->modify('+ ' . fake()->numberBetween(4, 16) . ' weeks');
        $contractPrice = fake()->randomFloat(2, 250000, 3500000);
        $actualSpend = fake()->randomFloat(2, 0, $contractPrice * 0.85);

        return [
            'name' => fake()->sentence(3),
            'description' => fake()->paragraph(),
            'client_name' => fake()->company(),
            'address' => fake()->streetAddress(),
            'barangay' => 'Barangay ' . fake()->numberBetween(1, 999),
            'city' => fake()->city(),
            'project_type' => fake()->randomElement(['Residential', 'Commercial', 'Industrial', 'Infrastructure']),
            'warranty_period' => '1 Year',
            'warranty_end_date' => (clone $startDate)->modify('+1 year')->format('Y-m-d'),
            'payment_status' => fake()->randomElement(['Paid', 'Partial']),
            'project_code' => sprintf('DEX-%d-%03d', now()->year, fake()->unique()->numberBetween(1, 999)),
            'status' => 'pending',
            'start_date' => $startDate->format('Y-m-d'),
            'target_completion_date' => $targetDate->format('Y-m-d'),
            'contract_price' => $contractPrice,
            'actual_spend' => $actualSpend,
            'created_by' => $user,
            'updated_by' => $user,
        ];
    }
}
