<?php

use App\Models\User;
use Database\Seeders\RoleSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

uses(RefreshDatabase::class);

beforeEach(function () {
    $this->seed(RoleSeeder::class);
});

test('admin can access user management page', function () {
    $admin = User::factory()->create(['password' => bcrypt('DexAdmin2026!')]);
    $admin->assignRole('Admin');

    $response = $this->actingAs($admin)->get(route('account.settings'));

    $response->assertStatus(200);
    $response->assertSee('User Management');
    $response->assertSee('+ Add User');
});

test('non-admin users cannot access user management CRUD', function () {
    $manager = User::factory()->create(['password' => bcrypt('password')]);
    $manager->assignRole('Manager');

    $response = $this->actingAs($manager)->get(route('account.users.create'));
    $response->assertStatus(403);
});

test('admin can view add user form with autogenerated employee number and predefined job titles', function () {
    $admin = User::factory()->create();
    $admin->assignRole('Admin');

    $response = $this->actingAs($admin)->get(route('account.users.create'));

    $response->assertStatus(200);
    $response->assertSee('Add User');
    $response->assertSee('EMP-2026002');
    $response->assertSee('First Name');
    $response->assertSee('Middle Name');
    $response->assertSee('Last Name');
    $response->assertSee('Birthdate');
    $response->assertSee('Manager');
    $response->assertSee('Engineer');
    $response->assertSee('CEO');
    $response->assertSee('Inventory personnel');
    $response->assertSee('Designers personnel');
    $response->assertSee('Others');
});

test('admin can create a user with autogenerated password format and login successfully', function () {
    $admin = User::factory()->create();
    $admin->assignRole('Admin');

    $userData = [
        'first_name' => 'John',
        'middle_name' => 'Fitzgerald',
        'last_name' => 'Smith',
        'birthdate' => '2000-08-15',
        'email' => 'john.smith@dex-pms.local',
        'job_title_choice' => 'Engineer',
        'role' => 'Manager',
    ];

    $response = $this->actingAs($admin)->post(route('account.users.store'), $userData);

    $response->assertRedirect(route('account.settings'));
    $response->assertSessionHas('status');

    $user = User::where('email', 'john.smith@dex-pms.local')->first();
    expect($user)->not->toBeNull();
    expect($user->first_name)->toBe('John');
    expect($user->middle_name)->toBe('Fitzgerald');
    expect($user->last_name)->toBe('Smith');
    expect($user->name)->toBe('John Fitzgerald Smith');
    expect($user->employee_number)->toBe('EMP-2026002');
    expect($user->job_title)->toBe('Engineer');
    expect($user->hasRole('Manager'))->toBeTrue();

    // Verify auto-generated password format: @ + lastname + DEX + birthyear -> @smithDEX2000
    expect(Hash::check('@smithDEX2000', $user->password))->toBeTrue();

    // Verify login with generated password
    Auth::logout();
    $loginResponse = $this->post(route('login.store'), [
        'email' => 'john.smith@dex-pms.local',
        'password' => '@smithDEX2000',
    ]);
    $loginResponse->assertRedirect(route('dashboard'));
    $this->assertAuthenticatedAs($user);
});

test('admin can create a user with custom job title when Others is selected', function () {
    $admin = User::factory()->create();
    $admin->assignRole('Admin');

    $userData = [
        'first_name' => 'Jane',
        'last_name' => 'Doe',
        'birthdate' => '1995-12-01',
        'email' => 'jane.doe@dex-pms.local',
        'job_title_choice' => 'Others',
        'job_title_other' => 'Lead Safety Architect',
        'role' => 'Manager',
    ];

    $response = $this->actingAs($admin)->post(route('account.users.store'), $userData);

    $response->assertRedirect(route('account.settings'));

    $user = User::where('email', 'jane.doe@dex-pms.local')->first();
    expect($user)->not->toBeNull();
    expect($user->job_title)->toBe('Lead Safety Architect');
    // Password should be @doeDEX1995
    expect(Hash::check('@doeDEX1995', $user->password))->toBeTrue();
});
