<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreProjectRequest;
use App\Http\Requests\UpdateProjectRequest;
use App\Models\Project;
use App\Services\ProjectService;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

/**
 * ProjectController — thin orchestrator.
 *
 * All business logic is in ProjectService.
 * Authorization is in ProjectPolicy (checked via $this->authorize()).
 * Validation is in StoreProjectRequest / UpdateProjectRequest.
 */
class ProjectController extends Controller
{
    public function __construct(
        private readonly ProjectService $projectService,
    ) {}

    /**
     * Display a paginated list of projects with optional status filter.
     * Eager-loads creator to avoid N+1 on the list view.
     */
    public function index(): View
    {
        $this->authorize('viewAny', Project::class);

        $status = request()->query('status');

        $projects = Project::query()
            ->with(['creator'])
            ->when($status, fn ($q) => $q->where('status', $status))
            ->orderByDesc('created_at')
            ->paginate(20)
            ->withQueryString();

        return view('projects.index', compact('projects', 'status'));
    }

    /** Show the create project form. */
    public function create(): View
    {
        $this->authorize('create', Project::class);

        return view('projects.create');
    }

    /**
     * Store a new project.
     * project_code is generated by ProjectService, not taken from input.
     */
    public function store(StoreProjectRequest $request): RedirectResponse
    {
        $this->authorize('create', Project::class);

        $project = $this->projectService->create($request->validated());

        return redirect()
            ->route('projects.show', $project)
            ->with('status', "Project "{$project->name}" created successfully.");
    }

    /**
     * Show project detail with eager-loaded history.
     * Status history is ordered by changed_at (ascending) in the relationship.
     */
    public function show(Project $project): View
    {
        $this->authorize('view', $project);

        $project->load(['creator', 'updater', 'statusHistory.changedBy']);

        return view('projects.show', compact('project'));
    }

    /** Show the edit project form. */
    public function edit(Project $project): View
    {
        $this->authorize('update', $project);

        return view('projects.edit', compact('project'));
    }

    /** Update project details (not status — transitions use a dedicated route). */
    public function update(UpdateProjectRequest $request, Project $project): RedirectResponse
    {
        $this->authorize('update', $project);

        $this->projectService->update($project, $request->validated());

        return redirect()
            ->route('projects.show', $project)
            ->with('status', "Project updated successfully.");
    }

    /**
     * Soft-delete a project.
     * Requires a confirmation step in the UI (per coding-standards.md).
     */
    public function destroy(Project $project): RedirectResponse
    {
        $this->authorize('delete', $project);

        $project->delete();

        return redirect()
            ->route('projects.index')
            ->with('status', "Project "{$project->name}" has been deleted.");
    }

    /**
     * Transition a project to the next allowed status.
     *
     * Accepts an optional 'notes' field (reason for the transition).
     * Transition validation happens in ProjectService::transition() —
     * invalid transitions return a 422 with an inline error.
     */
    public function transition(Project $project): RedirectResponse
    {
        $this->authorize('transition', $project);

        $validated = request()->validate([
            'status' => ['required', 'string', 'in:pending,ongoing,completed'],
            'notes' => ['nullable', 'string', 'max:500'],
        ]);

        $this->projectService->transition($project, $validated['status'], $validated['notes'] ?? null);

        return redirect()
            ->route('projects.show', $project)
            ->with('status', "Project status updated to "{$validated['status']}".");
    }
}
