<?php

namespace App\Models;

use App\Observers\ProjectObserver;
use Illuminate\Database\Eloquent\Attributes\ObservedBy;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

/**
 * Project Model
 *
 * Represents a project entity within the application.
 * Handles relationships to creator, updater, and status history.
 * Utilizes soft deletes and activity logging for audit trails.
 */
#[ObservedBy([ProjectObserver::class])]
class Project extends \Illuminate\Database\Eloquent\Model
{
    use HasFactory;
    use LogsActivity;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * status is intentionally included — ProjectService validates the
     * transition before calling update(), so it's safe to mass-assign.
     * project_code is generated by ProjectService and never comes from
     * user input; it is fillable only so the service can create the record.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'description',
        'client_name',
        'project_code',
        'status',
        'address',
        'barangay',
        'city',
        'project_type',
        'warranty_period',
        'warranty_end_date',
        'payment_status',
        'start_date',
        'target_completion_date',
        'contract_price',
        'actual_spend',
        'created_by',
        'updated_by',
    ];

    /**
     * Activity log configuration.
     *
     * Logs status, name, client_name, contract_price, and date changes for the audit trail.
     */
    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logOnly([
                'name',
                'client_name',
                'status',
                'contract_price',
                'actual_spend',
                'start_date',
                'target_completion_date',
                'address',
                'barangay',
                'city',
                'project_type',
                'warranty_period',
                'warranty_end_date',
                'payment_status',
            ])
            ->logOnlyDirty()
            ->dontSubmitEmptyLogs()
            ->useLogName('project');
    }

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'deleted_at' => 'datetime',
            'start_date' => 'date',
            'target_completion_date' => 'date',
            'warranty_end_date' => 'date',
            'contract_price' => 'decimal:2',
            'actual_spend' => 'decimal:2',
        ];
    }

    // ─── Accessors & Helpers ──────────────────────────────────────────────────

    /**
     * Get the formatted full site address / project location.
     */
    public function getFullAddressAttribute(): string
    {
        return collect([$this->address, $this->barangay, $this->city])
            ->filter(fn ($part) => filled($part))
            ->implode(', ');
    }

    /**
     * Remaining budget (Contract Price - Actual Spend).
     */
    public function getRemainingBudgetAttribute(): float
    {
        return (float) ($this->contract_price - $this->actual_spend);
    }

    /**
     * Spend percentage against contract price.
     */
    public function getSpendPercentageAttribute(): float
    {
        if ((float) $this->contract_price <= 0) {
            return 0.0;
        }

        return round(((float) $this->actual_spend / (float) $this->contract_price) * 100, 1);
    }

    /**
     * Costing health status indicator.
     */
    public function getCostingStatusAttribute(): string
    {
        if ($this->status === 'completed') {
            return 'Completed';
        }

        $pct = $this->spend_percentage;
        if ($pct > 100) {
            return 'Over Budget';
        }
        if ($pct >= 85) {
            return 'At Risk';
        }

        return 'On Track';
    }

    // ─── Relationships ────────────────────────────────────────────────────────

    /**
     * Get the user who created this project.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by')->withTrashed();
    }

    /**
     * Get the user who last updated this project.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function updater(): BelongsTo
    {
        return $this->belongsTo(User::class, 'updated_by')->withTrashed();
    }

    /**
     * Status change history — ordered chronologically.
     * Eager-load this on the project detail view.
     */
    public function statusHistory(): HasMany
    {
        return $this->hasMany(ProjectStatusHistory::class)->orderByDesc('changed_at')->orderByDesc('id');
    }

    /**
     * Currently assigned field personnel.
     */
    public function personnel(): HasMany
    {
        return $this->hasMany(Personnel::class);
    }

    /**
     * All field manpower who have worked on or are currently assigned to this project.
     */
    public function personnelHistory(): HasMany
    {
        return $this->hasMany(ProjectPersonnelHistory::class);
    }

    /**
     * Itemized costing entries for this project.
     */
    public function costs(): HasMany
    {
        return $this->hasMany(ProjectCost::class)->orderBy('id');
    }

    /**
     * Timeline major tasks for this project.
     */
    public function tasks(): HasMany
    {
        return $this->hasMany(ProjectTask::class)->orderBy('sort_order')->orderBy('start_date')->orderBy('id');
    }

    // ─── Scopes ───────────────────────────────────────────────────────────────

    /** @param \Illuminate\Database\Eloquent\Builder<Project> $query */
    public function scopePending(\Illuminate\Database\Eloquent\Builder $query): void
    {
        $query->where('status', 'pending');
    }

    /** @param \Illuminate\Database\Eloquent\Builder<Project> $query */
    public function scopeOngoing(\Illuminate\Database\Eloquent\Builder $query): void
    {
        $query->where('status', 'ongoing');
    }

    /** @param \Illuminate\Database\Eloquent\Builder<Project> $query */
    public function scopeDelayed(\Illuminate\Database\Eloquent\Builder $query): void
    {
        $query->where('status', 'delayed');
    }

    /** @param \Illuminate\Database\Eloquent\Builder<Project> $query */
    public function scopeCompleted(\Illuminate\Database\Eloquent\Builder $query): void
    {
        $query->where('status', 'completed');
    }

    /**
     * Get aggregate project counts in a single query across all statuses.
     *
     * @return array<string, int>
     */
    public static function getDashboardStats(): array
    {
        $raw = static::query()
            ->selectRaw("
                COUNT(*) as projects_total,
                SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) as projects_pending,
                SUM(CASE WHEN status = 'ongoing' THEN 1 ELSE 0 END) as projects_ongoing,
                SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) as projects_completed
            ")
            ->first();

        return [
            'projects_total' => (int) ($raw?->projects_total ?? 0),
            'projects_pending' => (int) ($raw?->projects_pending ?? 0),
            'projects_ongoing' => (int) ($raw?->projects_ongoing ?? 0),
            'projects_completed' => (int) ($raw?->projects_completed ?? 0),
        ];
    }
}
