<?php

namespace App\Models;

use App\Observers\ProjectObserver;
use Illuminate\Database\Eloquent\Attributes\ObservedBy;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

#[ObservedBy([ProjectObserver::class])]
class Project extends \Illuminate\Database\Eloquent\Model
{
    use HasFactory;
    use LogsActivity;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * status is intentionally included — ProjectService validates the
     * transition before calling update(), so it's safe to mass-assign.
     * project_code is excluded from fillable — generated by ProjectService,
     * never supplied by user input directly.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'description',
        'client_name',
        'status',
        'created_by',
        'updated_by',
    ];

    /**
     * Activity log configuration.
     *
     * Logs status, name, and client_name changes for the audit trail.
     * All three are important for history: status is the main event,
     * name/client changes are also meaningful for a reporting context.
     */
    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logOnly(['name', 'client_name', 'status'])
            ->logOnlyDirty()
            ->dontSubmitEmptyLogs()
            ->useLogName('project');
    }

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'deleted_at' => 'datetime',
        ];
    }

    // ─── Relationships ────────────────────────────────────────────────────────

    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function updater(): BelongsTo
    {
        return $this->belongsTo(User::class, 'updated_by');
    }

    /**
     * Status change history — ordered chronologically.
     * Eager-load this on the project detail view.
     */
    public function statusHistory(): HasMany
    {
        return $this->hasMany(ProjectStatusHistory::class)->orderBy('changed_at');
    }

    // ─── Scopes ───────────────────────────────────────────────────────────────

    /** @param \Illuminate\Database\Eloquent\Builder<Project> $query */
    public function scopePending(\Illuminate\Database\Eloquent\Builder $query): void
    {
        $query->where('status', 'pending');
    }

    /** @param \Illuminate\Database\Eloquent\Builder<Project> $query */
    public function scopeOngoing(\Illuminate\Database\Eloquent\Builder $query): void
    {
        $query->where('status', 'ongoing');
    }

    /** @param \Illuminate\Database\Eloquent\Builder<Project> $query */
    public function scopeCompleted(\Illuminate\Database\Eloquent\Builder $query): void
    {
        $query->where('status', 'completed');
    }
}
